# app/models/radd_alert.py
# This file defines the RADDAlert model, which represents alerts generated by the RADD system. Each alert includes information about the date of the alert, the estimated loss in hectares, the confidence level of the alert, and the geographic location of the alert. The model also includes a source field to indicate that the alert was generated by RADD, and a created_at timestamp to track when the alert was created in the database.
from sqlalchemy import Column, String, Float, DateTime
from geoalchemy2 import Geometry
from sqlalchemy.sql import func
import uuid
from app.db.base import Base

class RADDAlert(Base):
    __tablename__ = "radd_alerts"

    id = Column(String, primary_key=True, default=lambda: str(uuid.uuid4()))

    alert_date = Column(DateTime)
    loss_ha = Column(Float)
    confidence = Column(Float)

    geometry = Column(
        Geometry("POINT", srid=4326, spatial_index=True)
    )

    source = Column(String, default="RADD")

    created_at = Column(
        DateTime(timezone=True),
        server_default=func.now()
    )